version: '3.9'
services:
  backend:
    build: ./sfm/backend
    ports:
      - "8000:8000"
  mpfst:
    build:
      context: .
      args:
        NEXT_PUBLIC_SFM_WS: ws://backend:8000/ws
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SFM_WS=ws://backend:8000/ws
