version: '3.9'
services:
  backend:
    build:
      context: ./sfm/backend
      args:
        SFM_SHA: ${SFM_SHA:-dev}
    ports:
      - "8000:8000"
  mpfst:
    build:
      context: .
      args:
        SFM_WS: ws://localhost:8000/ws  # override with SFM_WS=ws://host/ws
        SFM_SHA: ${SFM_SHA:-dev}
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SFM_WS=ws://localhost:8000/ws
      - SFM_SHA=${SFM_SHA:-dev}
