// ─── MPFST CANONICAL DATA — Single Source of Truth ───
// Every number on mpfst.com comes from this file. Update here, updates everywhere.

export const STATS = {
  papers: 28,
  prlLetter: 1,
  domains: 30,
  parameters: 1,
  alpha: "6/5",
  alphaDecimal: 1.2,
  orcid: "0009-0005-7399-3204",
  author: "Freeman, Carlos W.",
  zenodoBase: "https://zenodo.org/records/",
  prlAccession: "LQ19911",
} as const;

export interface Paper {
  id: number;
  title: string;
  shortTitle: string;
  doi: string;
  field: string;
  keyResult: string;
  dataPoints: string;
  prediction: string;
  dataSource: string;
  howToReproduce: string;
  journalStatus?: string;
  domains: string[];
}

export const PAPERS: Paper[] = [
  {
    id: 1, title: "Non-local Brain Correlations via Transferred Potential",
    shortTitle: "Transferred Potential",
    doi: "10.5281/zenodo.18897624", field: "Neuroscience",
    keyResult: "7 pre-registered predictions from independent α = 6/5",
    dataPoints: "7 pre-registered predictions",
    prediction: "Cross-frequency coupling pattern in transferred potential EEG",
    dataSource: "Grinberg-Zylberbaum transferred potential dataset",
    howToReproduce: "Run coupled PDE on 11-node graph with α=6/5, compare cross-frequency output to transferred potential EEG recordings",
    journalStatus: "CHAOS-D-26-01867 (rejected)",
    domains: ["Transferred potential"],
  },
  {
    id: 2, title: "Sephirotic EEG Cross-Frequency Coupling",
    shortTitle: "EEG CFC",
    doi: "10.5281/zenodo.18848211", field: "Neuroscience",
    keyResult: "r = 0.767, p = 0.0097 across 109 subjects",
    dataPoints: "109 subjects",
    prediction: "CFC matrix structure from Sephirotic adjacency",
    dataSource: "PhysioNet EEG Motor Movement/Imagery Dataset (109 subjects)",
    howToReproduce: "Compute CFC matrices from PhysioNet EEG, compare to Sephirotic graph adjacency prediction with α=6/5",
    journalStatus: "CHAOS-D-26-01926 (rejected)",
    domains: ["EEG cross-frequency coupling"],
  },
  {
    id: 3, title: "MiniBooNE Neutrino Anomaly via Fractional Propagation",
    shortTitle: "MiniBooNE Neutrino",
    doi: "10.5281/zenodo.18884024", field: "Particle Physics",
    keyResult: "Low-energy excess reproduced with α = 6/5 fractional propagator",
    dataPoints: "MiniBooNE public dataset",
    prediction: "Low-energy neutrino excess from fractional Laplacian propagation",
    dataSource: "MiniBooNE public data release",
    howToReproduce: "Solve fractional propagator (-Δ)^(3/5) for neutrino oscillation, compare to MiniBooNE low-E bins",
    journalStatus: "CHAOS-D-26-02017 (rejected)",
    domains: ["Neutrino oscillations"],
  },
  {
    id: 4, title: "Galactic Rotation Curves Without Dark Matter",
    shortTitle: "Galactic Rotation",
    doi: "10.5281/zenodo.18884823", field: "Astrophysics",
    keyResult: "88/124 SPARC galaxies: MPFST PDE beats Newtonian (p < 10⁻⁶)",
    dataPoints: "124 SPARC galaxies",
    prediction: "Modified gravitational potential from fractional Laplacian at kpc scales",
    dataSource: "SPARC galaxy database (Lelli et al. 2016)",
    howToReproduce: "For each SPARC galaxy, solve fractional Poisson with α=6/5, compare rotation curve to observed. No dark matter halo.",
    domains: ["Galactic rotation curves"],
  },
  {
    id: 5, title: "LHC Dijet Angular Distributions",
    shortTitle: "LHC Dijets",
    doi: "10.5281/zenodo.18885114", field: "Particle Physics",
    keyResult: "Δχ² = 25.9, p = 2.4 × 10⁻⁶ (6.7σ) improvement over QCD",
    dataPoints: "LHC dijet angular data",
    prediction: "Fractional modification to QCD angular distributions",
    dataSource: "ATLAS/CMS dijet angular distributions (public)",
    howToReproduce: "Apply fractional propagator correction to QCD dijet prediction, fit to ATLAS angular data",
    domains: ["LHC dijets"],
  },
  {
    id: 6, title: "General Relativity Recovery as Low-Doping Limit",
    shortTitle: "GR Recovery",
    doi: "10.5281/zenodo.18885452", field: "Gravitational Physics",
    keyResult: "ε_doping < 1.15 × 10⁻⁴ at Cassini, transition at ~1 kpc",
    dataPoints: "Solar system precision tests",
    prediction: "GR emerges at α → 2 (small scales), deviates at α = 6/5 (large scales)",
    dataSource: "Cassini spacecraft Shapiro delay, Mercury perihelion precession",
    howToReproduce: "Show fractional gravity with α=6/5 recovers GR when ε_doping → 0, compute Cassini bound on doping parameter",
    domains: ["General relativity recovery"],
  },
  {
    id: 7, title: "Josephson Junction Phantom Voltage Offset",
    shortTitle: "JJ Phantom Voltage",
    doi: "10.5281/zenodo.18897625", field: "Condensed Matter",
    keyResult: "α_d = 1.2 predicts α_JJ ≈ 0.008 via inter-plane coupling",
    dataPoints: "Josephson junction voltage measurements",
    prediction: "Phantom voltage offset from inter-plane coupling at α = 6/5",
    dataSource: "Published JJ phantom voltage measurements",
    howToReproduce: "Compute α_JJ = (2-α_d)·ζ(α_d)/(2π·N^(α_d-1)) with α_d=1.2 and N≈5.6×10⁹",
    domains: ["Josephson junction phantom voltage", "JJ phantom offset"],
  },
  {
    id: 8, title: "Anomalous Qubit Decoherence Scaling",
    shortTitle: "Qubit Decoherence",
    doi: "10.5281/zenodo.18897605", field: "Quantum Computing",
    keyResult: "T₁ ∝ f^(−2.07±0.61) — MPFST −1.50 inside CI, QM −0.50 excluded",
    dataPoints: "15 superconducting qubits",
    prediction: "Decoherence scaling exponent from fractional Laplacian",
    dataSource: "IBM Quantum device T₁ data (15 qubits, published)",
    howToReproduce: "Fit T₁ vs frequency for IBM qubits, compare power-law exponent to MPFST prediction −(α+1)/α = −1.50",
    domains: ["Superconducting qubit decoherence"],
  },
  {
    id: 9, title: "Topological Origin of α = 6/5: Sephirotic Graph Eigenvalue",
    shortTitle: "Sephirotic Eigenvalue",
    doi: "10.5281/zenodo.18897608", field: "Mathematics",
    keyResult: "α = 6/5 is EXACT eigenvalue of 11-node graph (error < 10⁻¹⁶)",
    dataPoints: "Exact analytical proof",
    prediction: "α is not fitted — it is the 6th eigenvalue of the normalized Laplacian of the Sephirotic graph",
    dataSource: "Pure mathematics — graph spectral theory",
    howToReproduce: "Construct 11-node Sephirotic graph (10 Sephirot + Da'at, 24 edges), compute normalized Laplacian, verify λ₆ = 6/5 exactly",
    domains: ["Sephirotic graph topology"],
  },
  {
    id: 10, title: "Well-Posedness of the 11-Field Coupled Fractional PDE",
    shortTitle: "PDE Well-Posedness",
    doi: "10.5281/zenodo.18897626", field: "Mathematics",
    keyResult: "5 theorems: existence, uniqueness, energy bounds, spectral lock, global existence",
    dataPoints: "5 rigorous theorems",
    prediction: "The coupled PDE system is mathematically well-defined",
    dataSource: "Mathematical analysis (functional analysis, spectral theory)",
    howToReproduce: "Verify Picard contraction, Gronwall uniqueness, energy monotonicity, spectral matching numerically",
    domains: ["PDE well-posedness"],
  },
  {
    id: 11, title: "Emergent Quantization and Gravity from Fractional Dynamics",
    shortTitle: "Quantization & Quantum Gravity",
    doi: "10.5281/zenodo.18897627", field: "Quantum Gravity",
    keyResult: "Discrete energy spectrum + G(r) ~ r⁻¹·⁸ from same operator, QFT/GR recovered at α → 2",
    dataPoints: "6 computational demonstrations",
    prediction: "Quantization and gravity emerge from (-Δ)^(3/5) on 11-node topology",
    dataSource: "Computational — emergent from topology",
    howToReproduce: "Diagonalize (-Δ)^(α/2) on Sephirotic graph, verify discrete spectrum, compute Green's function, show QFT/GR recovery at α→2",
    domains: ["Quantization & quantum gravity"],
  },
  {
    id: 12, title: "Fractional Transport in Fusion Plasmas",
    shortTitle: "Fusion Plasma Transport",
    doi: "10.5281/zenodo.18897630", field: "Plasma Physics",
    keyResult: "χ² = 7.75, dof = 55, p ≈ 1.000 — zero free parameters",
    dataPoints: "55 measurements from 15 tokamaks",
    prediction: "PSD β=1.2, Hurst H=0.6, ELM Weibull k=1.2, pedestal −5/6, transport 1.2",
    dataSource: "Published tokamak data: DIII-D, JET, ASDEX-U, NSTX, EAST, KSTAR, etc.",
    howToReproduce: "Compile published tokamak observables, compare each to zero-parameter MPFST predictions derived from α=6/5",
    domains: ["Fusion plasma transport"],
  },
  {
    id: 13, title: "Power-Law Post-Merger Decay in Gravitational Waves",
    shortTitle: "GW Echoes",
    doi: "10.5281/zenodo.18900993", field: "Gravitational Physics",
    keyResult: "73/109 events MPFST wins (67%), p = 9.16 × 10⁻⁵, combined Fisher 5.8σ",
    dataPoints: "486 measurements, 243 events",
    prediction: "Power-law ringdown tail from fractional dissipation, not exponential",
    dataSource: "GWOSC (Gravitational Wave Open Science Center) public strain data",
    howToReproduce: "Download LIGO/Virgo strain data via gwpy, extract post-merger envelope, fit exponential vs power-law, compare BIC",
    domains: ["Gravitational wave echoes"],
  },
  {
    id: 14, title: "Dynamical Dimensional Reduction via Fractional Stückelberg Mechanism",
    shortTitle: "Dimensional Reduction",
    doi: "10.5281/zenodo.19390482", field: "Theoretical Physics",
    keyResult: "Spectral gap Δλ = 0.458 splits 11 modes → 2 light + 9 heavy (40% stronger on canonical graph)",
    dataPoints: "Analytical + numerical",
    prediction: "11 planes reduce to 2 effective modes: gravity (universal) + gauge (bilateral)",
    dataSource: "Spectral analysis of Sephirotic graph Laplacian",
    howToReproduce: "Compute full spectrum of Sephirotic Laplacian, identify spectral gap, evolve coupled system, measure energy in light vs heavy modes",
    domains: ["Dimensional reduction"],
  },
  {
    id: 15, title: "Stochastic Extensions of the MPFST Coupled PDE System",
    shortTitle: "Stochastic PDE",
    doi: "10.5281/zenodo.19390485", field: "Mathematics",
    keyResult: "Spectral gap (Δλ = 0.458) survives noise, Kramers escape R² = 0.997, stochastic resonance at σ ≈ 0.3",
    dataPoints: "6 computational tests",
    prediction: "Sephirotic structure is robust under stochastic perturbation",
    dataSource: "Computational — stochastic PDE simulation",
    howToReproduce: "Add Gaussian noise to MPFST PDE, verify spectral gap preservation, measure Kramers rates, find stochastic resonance peak",
    domains: ["Stochastic PDE robustness"],
  },
  {
    id: 16, title: "Accelerated Cosmic Expansion from Fractional Gravity",
    shortTitle: "Dark Energy / Cosmology",
    doi: "10.5281/zenodo.18930436", field: "Cosmology",
    keyResult: "w = −11/15 from topology; Δχ² = 0.32 vs ΛCDM on 1,590 supernovae",
    dataPoints: "1,590 Pantheon+ Type Ia supernovae",
    prediction: "Dark energy EOS w = −(2α−1)/(2α+1) = −11/15 ≈ −0.733",
    dataSource: "Pantheon+ SN Ia dataset (Scolnic et al. 2022)",
    howToReproduce: "Derive w from fractional Friedmann equation, fit Pantheon+ distance moduli, compare to ΛCDM",
    domains: ["Dark energy / cosmic expansion"],
  },
  {
    id: 17, title: "Anomalous Self-Energy Scaling in Cuprates and Graphene",
    shortTitle: "Anomalous Transport",
    doi: "10.5281/zenodo.19027629", field: "Condensed Matter",
    keyResult: "25 measurements: MPFST χ² = 4.4 vs MFL χ² = 33.5 — 7.6× better",
    dataPoints: "25 measurements across cuprates + graphene",
    prediction: "Optical self-energy exponent β = 2 − α = 4/5 = 0.800",
    dataSource: "Published ARPES/IR/Raman data: BSCCO, YBCO, Tl-2201, Hg-1201, LSCO, graphene",
    howToReproduce: "Compile published optical self-energy exponents, compare weighted mean to MPFST β=0.800 vs MFL β=1.0",
    domains: ["Cuprate superconductivity", "Graphene transport"],
  },
  {
    id: 18, title: "Black Hole Entropy Corrections from Fractional Dynamics",
    shortTitle: "Black Hole Thermodynamics",
    doi: "10.5281/zenodo.18932512", field: "Quantum Gravity",
    keyResult: "c_log = −2/3 (matches Asymptotic Safety exactly); evaporation τ ~ M³·²",
    dataPoints: "Analytical derivation",
    prediction: "Logarithmic entropy correction c_log = −(d_s/2 − 1) = −2/3",
    dataSource: "Comparison to Asymptotic Safety, LQG, string theory predictions",
    howToReproduce: "Compute spectral dimension d_s = 2α/2 on 2D horizon, derive c_log, compare to AS/LQG/strings",
    domains: ["Black hole thermodynamics"],
  },
  {
    id: 19, title: "Topological Constraints on Bioelectric Morphogenesis",
    shortTitle: "Bioelectric Morphogenesis",
    doi: "10.5281/zenodo.18950516", field: "Biology",
    keyResult: "AP before LR (3.1:1 energy), size-independent regeneration, Fisher p = 0.0014",
    dataPoints: "Sephirotic mode analysis",
    prediction: "Mode hierarchy predicts developmental axis sequence and size-independent regeneration",
    dataSource: "Levin lab bioelectric patterning data, planaria regeneration literature",
    howToReproduce: "Compute Sephirotic eigenmodes, identify bilateral Mode 1, verify AP→LR ordering, compare spectral gap to regeneration data",
    domains: ["Bioelectric morphogenesis"],
  },
  {
    id: 20, title: "Universal Eigenvalue Convergence in Microtubule Lattices",
    shortTitle: "Microtubule Topology",
    doi: "10.5281/zenodo.18951587", field: "Biophysics",
    keyResult: "All 5 PF types (11–15) converge to λ ≈ 1.200 at 9,150 nodes",
    dataPoints: "5 protofilament types, 8 topologies, 100K null test",
    prediction: "λ = 6/5 is universal across all microtubule lattice architectures",
    dataSource: "Microtubule lattice geometry (Amos & Klug, Chrétien & Wade)",
    howToReproduce: "Build helical MT lattice graphs for 11–15 PF types, compute normalized Laplacian eigenvalues, verify convergence to 1.200",
    domains: ["Microtubule lattice topology"],
  },
  {
    id: 21, title: "Low-Energy Nuclear Reactions from Fractional Tunneling",
    shortTitle: "LENR / Cold Fusion",
    doi: "10.5281/zenodo.18973585", field: "Nuclear Physics",
    keyResult: "2,697 orders of magnitude tunneling enhancement; 23.7 MeV/He-4 predicted",
    dataPoints: "Theoretical + comparison to 8 LENR signatures",
    prediction: "Power-law tunneling tails from (-Δ)^(3/5) replace exponential suppression",
    dataSource: "Published LENR experimental data, d–d Coulomb barrier parameters",
    howToReproduce: "Solve fractional Schrödinger for d–d system with α=6/5, compute tunneling probability, compare to standard WKB",
    domains: ["LENR / cold fusion"],
  },
  {
    id: 22, title: "Topological Peristalsis in Microtubule Lumens",
    shortTitle: "MT Lumen Pump",
    doi: "10.5281/zenodo.19076621", field: "Biophysics",
    keyResult: "121× Ca²⁺ enhancement (thermal), 302,671× (driven); Meyer-Overton r = 0.995",
    dataPoints: "Anesthetic correlations + ion transport simulations",
    prediction: "Bilateral eigenmode creates peristaltic pump; anesthesia disrupts spectral gap",
    dataSource: "Meyer-Overton correlation data, microtubule structural biology literature",
    howToReproduce: "Build 13-PF MT lattice, compute bilateral eigenmode, simulate Ca²⁺ transport with mode-driven peristalsis",
    domains: ["Microtubule ion transport"],
  },
  {
    id: 23, title: "Anomalous Power-Law Behavior in Atomic Form Factors",
    shortTitle: "Atomic Form Factors",
    doi: "10.5281/zenodo.19027386", field: "Atomic Physics",
    keyResult: "β = 1.411 ± 0.144 across 11 atoms — 2.8× closer to MPFST than QM",
    dataPoints: "11 atoms (H through Au), 500 null tests",
    prediction: "Form factor cusp F(Q) ~ 1 − c|Q|^(6/5) instead of smooth parabola",
    dataSource: "Waasmaier-Kirfel atomic form factor coefficients (IUCr Tables)",
    howToReproduce: "Fit f₀(Q)/f₀(0) = 1 − c·Q^β near Q=0 for each element using W-K coefficients. Compare free β to 1.2 vs 2.0.",
    domains: ["Atomic form factors"],
  },
  {
    id: 24, title: "First-Principles Derivation of the Sephirotic Graph: Three Axioms to α = 6/5",
    shortTitle: "First-Principles Derivation",
    doi: "10.5281/zenodo.19041034", field: "Mathematics",
    keyResult: "3 axioms → d=3 forced → Tree of Life → λ₆ = 6/5 exact (error 2.22 × 10⁻¹⁶)",
    dataPoints: "Uniqueness: 0/500,000 random graphs match",
    prediction: "The Sephirotic graph is the UNIQUE topology emerging from (existence, isotropy, self-reference)",
    dataSource: "Pure mathematics — constructive geometry + graph spectral theory",
    howToReproduce: "Follow axiom chain: 3 axioms → d=3 → Tree of Life (canonical Paper 9 graph). Verify spatial eigenvalues (0.908, 1.200, 1.542) and λ₆ = 6/5 exactly",
    domains: ["First-principles derivation"],
  },
  {
    id: 25, title: "Bioelectric Channel Topology: Eight Internal Modes Predict Levin's Signaling Channels",
    shortTitle: "Bioelectric Channels",
    doi: "10.5281/zenodo.19042388", field: "Biology",
    keyResult: "8 internal modes map 1:1 to Levin's 8 bioelectric channels; 7/8 confirmed by knockouts",
    dataPoints: "8 channel mappings, 100K null test",
    prediction: "8+3 mode split: 8 internal = 8 bioelectric channels, 3 spatial = developmental axes",
    dataSource: "Levin lab published bioelectric channel experiments",
    howToReproduce: "Compute eigenmodes of Paper 24 canonical graph, classify symmetric (internal) vs anti-symmetric (spatial), map to Levin's channels via node semantics",
    domains: ["Bioelectric channel topology"],
  },
  {
    id: 26, title: "Three-Mode Spatial Template for GW Post-Merger Decay",
    shortTitle: "GW Spatial Modes",
    doi: "10.5281/zenodo.19043711", field: "Gravitational Physics",
    keyResult: "8/8 high-SNR wins (100%); combined Fisher p = 3.2 × 10⁻⁶ (4.7σ)",
    dataPoints: "486 measurements, 243 LIGO/Virgo events",
    prediction: "3-mode spatial template h(t) = Σ Aₖ t^(-λₖ/2) with eigenvalues [0.908, 1.200, 1.542]",
    dataSource: "GWOSC public strain data (O1–O4)",
    howToReproduce: "Download LIGO strain via gwpy, extract post-merger, fit 6 models including 3-mode spatial template, compare BIC",
    domains: ["GW spatial mode superposition"],
  },
  {
    id: 27, title: "Spectral Exponents of Intracranial EEG Cluster Near Sephirotic Eigenvalues: Region-Specific 1/f Dynamics from Graph Topology",
    shortTitle: "iEEG Spectral Eigenvalues",
    doi: "10.5281/zenodo.19341982", field: "Neuroscience",
    keyResult: "β_k = 2α/λ_k: χ² = 0.74, p = 0.994 — zero free parameters. 575 iEEG channels across 6 brain regions; Kruskal-Wallis H=68.68, p=1.93×10⁻¹³",
    dataPoints: "575 iEEG channels across 6 brain regions from 10 subjects (OpenNeuro ds004752) + 576 channels from 7 subjects (figshare.30434683)",
    prediction: "β_k = 2α/λ_k — spectral exponents derived from Sephirotic eigenvalues with zero free parameters",
    dataSource: "OpenNeuro ds004752 (Fedele et al. stereo-EEG) + figshare.30434683 (Banaie Boroujeni et al. 2025, Nature Neuroscience)",
    howToReproduce: "Download ds004752, compute 1/f spectral exponent per channel (Welch PSD, 2-50 Hz), group by anatomical label, compare to derived β_k = 2α/λ_k for each Sephirotic eigenvalue",
    domains: ["iEEG spectral eigenvalue mapping", "Region-specific 1/f dynamics"],
  },
  {
    id: 28, title: "Topological Origin of Frequency-Dependent Cortical Propagation: Independent Confirmation from 608-Subject MEG",
    shortTitle: "MEG Directional Propagation",
    doi: "10.5281/zenodo.19341983", field: "Neuroscience",
    keyResult: "608-subject MEG independently confirms Paper 2v2 prediction: slow=upstream, fast=downstream (d=0.73)",
    dataPoints: "608 subjects (Liu, Wiesman & Baillet 2026, bioRxiv)",
    prediction: "Frequency-dependent directional asymmetry from Sephirotic graph topology",
    dataSource: "Liu, Wiesman & Baillet (2026) bioRxiv — 608-subject MEG",
    howToReproduce: "Compare Paper 2v2 prediction of frequency-dependent directional asymmetry to Liu et al. MEG data. No post-hoc fitting needed — prediction existed before their data.",
    domains: ["MEG frequency-dependent directional propagation"],
  },
];

export const PRL = {
  title: "One Topological Constant Predicts Thirteen Physical Domains",
  subtitle: "Fractional Dynamics on an 11-Node Graph",
  doi: "10.5281/zenodo.18898117",
  accession: "LQ19911",
  journal: "Physical Review Letters",
  status: "Desk rejected",
};

export const FIELDS = [
  { name: "Particle Physics", color: "#f97316", papers: [3, 5] },
  { name: "Astrophysics", color: "#3b82f6", papers: [4, 13] },
  { name: "Cosmology", color: "#6366f1", papers: [16, 18] },
  { name: "Gravitational Physics", color: "#8b5cf6", papers: [6, 13, 26] },
  { name: "Neuroscience", color: "#ec4899", papers: [1, 2, 27, 28] },
  { name: "Condensed Matter", color: "#14b8a6", papers: [7, 8, 17] },
  { name: "Plasma Physics", color: "#f59e0b", papers: [12] },
  { name: "Biology", color: "#22c55e", papers: [19, 25] },
  { name: "Biophysics", color: "#10b981", papers: [20, 22] },
  { name: "Nuclear Physics", color: "#ef4444", papers: [21] },
  { name: "Atomic Physics", color: "#a855f7", papers: [23] },
  { name: "Quantum Gravity", color: "#7c3aed", papers: [11, 18] },
  { name: "Mathematics", color: "#64748b", papers: [9, 10, 15, 24] },
  { name: "Theoretical Physics", color: "#94a3b8", papers: [14] },
  { name: "Quantum Computing", color: "#06b6d4", papers: [8] },
];

export const DOMAINS: string[] = [
  "Neutrino oscillations (MiniBooNE)",
  "Galactic rotation curves",
  "EEG cross-frequency coupling",
  "Transferred potential",
  "LHC dijets (collider physics)",
  "General relativity recovery",
  "Josephson junction phantom voltage",
  "JJ phantom offset (α_d → α_JJ mapping)",
  "Superconducting qubit decoherence",
  "Sephirotic graph topology (first-principles derivation)",
  "PDE well-posedness (mathematical foundation)",
  "Quantization & quantum gravity",
  "Fusion plasma transport (55 measurements, 15 tokamaks)",
  "Gravitational wave echoes (486 measurements, 3.7σ)",
  "Dimensional reduction (11 → 2 modes)",
  "Stochastic PDE robustness",
  "Dark energy / cosmic expansion",
  "Cuprate superconductivity",
  "Black hole thermodynamics",
  "Bioelectric morphogenesis",
  "Microtubule lattice topology",
  "LENR / cold fusion",
  "Microtubule ion transport",
  "Atomic form factors",
  "First-principles derivation (3 axioms → Tree of Life → α = 6/5)",
  "Bioelectric channel topology (8 internal modes = 8 Levin channels)",
  "GW spatial mode superposition (3 eigenvalues, 8/8 high-SNR, 4.7σ)",
  "iEEG spectral eigenvalue mapping (575 channels, 6 regions, p = 0.0037)",
  "Region-specific 1/f dynamics (Kruskal-Wallis H=68.68, p = 1.93×10⁻¹³)",
  "MEG frequency-dependent directional propagation (608 subjects, d = 0.73, independent confirmation)",
];

// Helper to get Zenodo URL from DOI
export const zenodoUrl = (doi: string) => `https://zenodo.org/records/${doi.split('.').pop()}`;
