import React, { useState, useRef, useEffect } from "react";
import Layout from "@/components/Layout";
import { STATS } from "@/components/data";

interface Message {
  role: "user" | "assistant";
  text: string;
}

const SUGGESTIONS = [
  "What is MPFST in simple terms?",
  "How does α = 6/5 come from topology?",
  "What experimental evidence supports MPFST?",
  "How does MPFST explain dark matter?",
  "What would disprove MPFST?",
  "How do I reproduce the fusion plasma results?",
];

export default function ChatPage() {
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const [sessionId] = useState(() => Math.random().toString(36).slice(2));
  const endRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    endRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  async function send(text?: string) {
    const msg = (text || input).trim();
    if (!msg || loading) return;

    const userMsg: Message = { role: "user", text: msg };
    setMessages(prev => [...prev, userMsg]);
    setInput("");
    setLoading(true);

    try {
      const res = await fetch("/api/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ message: msg, sessionId }),
      });

      const data = await res.json();

      if (!res.ok) {
        setMessages(prev => [
          ...prev,
          { role: "assistant", text: data.error || "Something went wrong. Please try again." },
        ]);
      } else {
        setMessages(prev => [
          ...prev,
          { role: "assistant", text: data.reply },
        ]);
      }
    } catch {
      setMessages(prev => [
        ...prev,
        { role: "assistant", text: "Network error. Please check your connection and try again." },
      ]);
    } finally {
      setLoading(false);
      inputRef.current?.focus();
    }
  }

  return (
    <Layout
      title="Ask MPFST — AI Research Assistant"
      description="Ask questions about Multi-Plane Field Syntergic Theory"
    >
      <div style={{ maxWidth: 800, margin: "0 auto", display: "flex", flexDirection: "column", minHeight: "70vh" }}>
        <div style={{ marginBottom: 24 }}>
          <h1 style={{ fontSize: 28, fontWeight: 700, marginBottom: 8 }}>Ask MPFST</h1>
          <p style={{ color: "#999", fontSize: 14 }}>
            AI research assistant trained on all {STATS.papers} papers + PRL letter.
            Answers are generated by Claude (Anthropic) with full knowledge of every MPFST publication.
            This is an independent instance — not connected to any other system.
          </p>
        </div>

        {/* Messages */}
        <div style={{
          flex: 1,
          overflowY: "auto",
          marginBottom: 16,
          padding: "0 4px",
          minHeight: 300,
        }}>
          {messages.length === 0 && (
            <div style={{ padding: "40px 0" }}>
              <p style={{ color: "#888", marginBottom: 20, fontSize: 15 }}>
                Ask anything about MPFST — the theory, the math, the experiments, how to reproduce results, or what it predicts.
              </p>
              <div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>
                {SUGGESTIONS.map((s, i) => (
                  <button
                    key={i}
                    onClick={() => send(s)}
                    style={{
                      padding: "8px 14px",
                      borderRadius: 20,
                      border: "1px solid #333",
                      background: "transparent",
                      color: "#ccc",
                      fontSize: 13,
                      cursor: "pointer",
                      transition: "all 0.2s",
                    }}
                    onMouseEnter={e => {
                      e.currentTarget.style.borderColor = "#c9a227";
                      e.currentTarget.style.color = "#c9a227";
                    }}
                    onMouseLeave={e => {
                      e.currentTarget.style.borderColor = "#333";
                      e.currentTarget.style.color = "#ccc";
                    }}
                  >
                    {s}
                  </button>
                ))}
              </div>
            </div>
          )}

          {messages.map((m, i) => (
            <div
              key={i}
              style={{
                display: "flex",
                justifyContent: m.role === "user" ? "flex-end" : "flex-start",
                marginBottom: 12,
              }}
            >
              <div
                style={{
                  maxWidth: "80%",
                  padding: "12px 16px",
                  borderRadius: m.role === "user" ? "16px 16px 4px 16px" : "16px 16px 16px 4px",
                  background: m.role === "user" ? "#c9a227" : "#1a1a2e",
                  color: m.role === "user" ? "#000" : "#e0e0e0",
                  fontSize: 14,
                  lineHeight: 1.6,
                  whiteSpace: "pre-wrap",
                  wordBreak: "break-word",
                  border: m.role === "assistant" ? "1px solid #2a2a3e" : "none",
                }}
              >
                {m.text}
              </div>
            </div>
          ))}

          {loading && (
            <div style={{ display: "flex", justifyContent: "flex-start", marginBottom: 12 }}>
              <div
                style={{
                  padding: "12px 16px",
                  borderRadius: "16px 16px 16px 4px",
                  background: "#1a1a2e",
                  border: "1px solid #2a2a3e",
                  color: "#888",
                  fontSize: 14,
                }}
              >
                Thinking…
              </div>
            </div>
          )}

          <div ref={endRef} />
        </div>

        {/* Input */}
        <div style={{
          display: "flex",
          gap: 8,
          padding: "12px 0",
          borderTop: "1px solid #222",
        }}>
          <input
            ref={inputRef}
            type="text"
            value={input}
            onChange={e => setInput(e.target.value)}
            onKeyDown={e => e.key === "Enter" && send()}
            placeholder="Ask about MPFST..."
            disabled={loading}
            style={{
              flex: 1,
              padding: "12px 16px",
              borderRadius: 24,
              border: "1px solid #333",
              background: "#111",
              color: "#fff",
              fontSize: 15,
              outline: "none",
            }}
            autoFocus
          />
          <button
            onClick={() => send()}
            disabled={loading || !input.trim()}
            style={{
              padding: "12px 24px",
              borderRadius: 24,
              border: "none",
              background: loading || !input.trim() ? "#333" : "#c9a227",
              color: loading || !input.trim() ? "#666" : "#000",
              fontWeight: 600,
              fontSize: 15,
              cursor: loading || !input.trim() ? "default" : "pointer",
              transition: "all 0.2s",
            }}
          >
            {loading ? "…" : "Ask"}
          </button>
        </div>
      </div>
    </Layout>
  );
}
