name: CI
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "SFM_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
      - run: npm test
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r sfm/backend/requirements.txt pytest-asyncio
      - run: pytest -q
